/* eslint-disable no-unused-vars */
/** Type definitions for ModFetch configuration */

export type ModLoader = 'forge' | 'neoforge' | 'fabric' | 'quilt';
export type OutputFormat = 'zip' | 'mrpack';
export type MrpackMode = 'download' | 'reference';
export type FileType = 'mod' | 'file' | 'resourcepack' | 'shaderpack';

export interface ModEntry {
  id?: string;
  slug?: string;
  version?: string;
  only_version?: string | string[];
  feature?: string | string[];
}

export interface ExtraUrl {
  url: string;
  filename?: string;
  type?: FileType;
  sha1?: string;
  only_version?: string | string[];
  feature?: string | string[];
}

export interface MetadataConfig {
  name: string;
  version: string;
  description: string;
}

export interface MinecraftConfig {
  version: string[];
  mod_loader: ModLoader | ModLoader[];
  mods: (string | ModEntry)[];
  resourcepacks: (string | ModEntry)[];
  shaderpacks: (string | ModEntry)[];
  extra_urls: ExtraUrl[];
}

export interface OutputConfig {
  download_dir: string;
  format: OutputFormat[];
  mrpack_modes: MrpackMode[];
}

export interface PluginConfig {
  enabled: string[];
  configs: Record<string, Record<string, unknown>>;
}

export interface ParentConfig {
  url: string;
  format: string;
}

export interface ModFetchConfig {
  metadata: MetadataConfig;
  minecraft: MinecraftConfig;
  output: OutputConfig;
  max_concurrent?: number;
  max_retries?: number;
  retry_delay?: number;
  features?: string[];
  parent_configs?: ParentConfig[];
  plugins?: PluginConfig;
}

/** Create a default config */
export function createDefaultConfig(): ModFetchConfig {
  return {
    metadata: {
      name: 'ModFetch Pack',
      version: '1.0.0',
      description: 'A modpack generated by ModFetch',
    },
    minecraft: {
      version: [],
      mod_loader: ['fabric'],
      mods: [],
      resourcepacks: [],
      shaderpacks: [],
      extra_urls: [],
    },
    output: {
      download_dir: 'downloads',
      format: ['mrpack'],
      mrpack_modes: ['download'],
    },
    max_concurrent: 5,
    max_retries: 3,
    retry_delay: 1.0,
    features: [],
    plugins: {
      enabled: [],
      configs: {},
    },
  };
}
