import sys
import toml
from PySide6.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QComboBox,
    QTextEdit,
    QPushButton,
    QFileDialog,
    QGroupBox,
    QFormLayout,
    QCheckBox,
    QListWidget,
    QListWidgetItem,
    QMessageBox,
    QTabWidget,
)
from PySide6.QtCore import Qt


class ModFetchGui(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("ModFetch Config Generator")
        self.resize(600, 750)
        self.apply_style()
        self.init_ui()

    def is_dark_mode(self):
        """检测系统是否处于暗色模式"""
        palette = QApplication.palette()
        color = palette.color(palette.ColorGroup.Active, palette.ColorRole.WindowText)
        return color.lightness() > 128

    def apply_style(self):
        # 现代化的 QSS
        dark = self.is_dark_mode()

        if dark:
            # 暗色配色
            bg_main = "#1c1c1e"
            bg_pane = "#2c2c2e"
            bg_input = "#1c1c1e"
            border = "#3a3a3c"
            text = "#ffffff"
            tab_inactive = "#3a3a3c"
        else:
            # 浅色配色
            bg_main = "#f5f5f7"
            bg_pane = "#ffffff"
            bg_input = "#ffffff"
            border = "#d1d1d6"
            text = "#000000"
            tab_inactive = "#e5e5ea"

        qss = f"""
        QMainWindow {{
            background-color: {bg_main};
            color: {text};
        }}
        QLabel {{
            color: {text};
        }}
        QTabWidget::pane {{
            border: 1px solid {border};
            background: {bg_pane};
            border-radius: 8px;
            top: -1px;
        }}
        QTabBar::tab {{
            background: {tab_inactive};
            border: 1px solid {border};
            padding: 8px 16px;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            margin-right: 2px;
            color: {text};
        }}
        QTabBar::tab:selected {{
            background: {bg_pane};
            border-bottom-color: {bg_pane};
            font-weight: bold;
        }}
        QGroupBox {{
            font-weight: bold;
            border: 1px solid {border};
            border-radius: 8px;
            margin-top: 12px;
            padding-top: 12px;
            background-color: {bg_pane};
            color: {text};
        }}
        QGroupBox::title {{
            subcontrol-origin: margin;
            left: 10px;
            padding: 0 5px;
        }}
        QLineEdit, QTextEdit, QComboBox, QListWidget {{
            border: 1px solid {border};
            border-radius: 4px;
            padding: 5px;
            background-color: {bg_input};
            color: {text};
            selection-background-color: #007aff;
        }}
        QLineEdit:focus, QTextEdit:focus {{
            border: 1.5px solid #007aff;
        }}
        QPushButton {{
            background-color: #007aff;
            color: white;
            border-radius: 6px;
            padding: 8px 16px;
            font-weight: bold;
            font-size: 13px;
        }}
        QPushButton:hover {{
            background-color: #0063cc;
        }}
        QPushButton:pressed {{
            background-color: #0051a8;
        }}
        QPushButton#secondary {{
            background-color: {tab_inactive};
            color: #007aff;
        }}
        QPushButton#danger {{
            background-color: #ff3b30;
            color: white;
        }}
        """
        self.setStyleSheet(qss)

    def init_ui(self):

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QVBoxLayout(central_widget)

        tabs = QTabWidget()
        main_layout.addWidget(tabs)

        # --- Metadata Tab ---
        metadata_tab = QWidget()
        metadata_layout = QFormLayout(metadata_tab)
        self.name_edit = QLineEdit("ModFetch Pack")
        self.version_edit = QLineEdit("1.0.0")
        self.desc_edit = QTextEdit("A modpack generated by ModFetch")
        self.desc_edit.setMaximumHeight(100)
        self.authors_edit = QLineEdit("ModFetch User")

        metadata_layout.addRow("Name:", self.name_edit)
        metadata_layout.addRow("Version:", self.version_edit)
        metadata_layout.addRow("Description:", self.desc_edit)
        metadata_layout.addRow("Authors:", self.authors_edit)
        tabs.addTab(metadata_tab, "Metadata")

        # --- Minecraft Tab ---
        minecraft_tab = QWidget()
        minecraft_layout = QVBoxLayout(minecraft_tab)

        # Version & Loader
        config_group = QGroupBox("Core Config")
        config_form = QFormLayout(config_group)
        self.mc_version_edit = QLineEdit("1.21.4")
        self.mc_version_edit.setPlaceholderText("Comma separated, e.g. 1.21.4, 1.21.1")
        self.loader_combo = QComboBox()
        self.loader_combo.addItems(["fabric", "forge", "neoforge", "quilt"])
        config_form.addRow("MC Version(s):", self.mc_version_edit)
        config_form.addRow("Mod Loader:", self.loader_combo)
        minecraft_layout.addWidget(config_group)

        # Mods list
        mods_group = QGroupBox("Mods / Resources / Shaders")
        mods_layout = QVBoxLayout(mods_group)

        input_layout = QHBoxLayout()
        self.mod_input = QLineEdit()
        self.mod_input.setPlaceholderText("Enter mod slug/ID")
        self.type_combo = QComboBox()
        self.type_combo.addItems(["Mods", "Resourcepacks", "Shaderpacks"])
        add_btn = QPushButton("Add")
        add_btn.clicked.connect(self.add_mod)
        input_layout.addWidget(self.mod_input)
        input_layout.addWidget(self.type_combo)
        input_layout.addWidget(add_btn)
        mods_layout.addLayout(input_layout)

        self.mod_list = QListWidget()
        mods_layout.addWidget(self.mod_list)

        remove_btn = QPushButton("Remove Selected")
        remove_btn.setObjectName("danger")
        remove_btn.clicked.connect(self.remove_mod)
        mods_layout.addWidget(remove_btn)

        minecraft_layout.addWidget(mods_group)
        tabs.addTab(minecraft_tab, "Minecraft")

        # --- Output Tab ---
        output_tab = QWidget()
        output_layout = QFormLayout(output_tab)
        self.download_dir_edit = QLineEdit("./downloads")
        self.format_zip = QCheckBox("ZIP")
        self.format_zip.setChecked(True)
        self.format_mrpack = QCheckBox("MRPACK")

        output_layout.addRow("Download Dir:", self.download_dir_edit)
        output_layout.addRow("Format:", self.format_zip)
        output_layout.addRow("", self.format_mrpack)
        tabs.addTab(output_tab, "Output")

        # --- Action Buttons ---
        btn_layout = QHBoxLayout()
        save_btn = QPushButton("Generate mods.toml")
        save_btn.clicked.connect(self.generate_toml)
        btn_layout.addWidget(save_btn)
        main_layout.addLayout(btn_layout)

    def add_mod(self):
        mod = self.mod_input.text().strip()
        if not mod:
            return
        mod_type = self.type_combo.currentText()
        item_text = f"[{mod_type}] {mod}"

        # Check for duplicates
        if self.mod_list.findItems(item_text, Qt.MatchFlag.MatchExactly):
            return

        item = QListWidgetItem(item_text)
        item.setData(Qt.ItemDataRole.UserRole, (mod_type, mod))
        self.mod_list.addItem(item)
        self.mod_input.clear()

    def remove_mod(self):
        for item in self.mod_list.selectedItems():
            self.mod_list.takeItem(self.mod_list.row(item))

    def generate_toml(self):
        try:
            # Parse versions
            versions = [
                v.strip() for v in self.mc_version_edit.text().split(",") if v.strip()
            ]
            if not versions:
                QMessageBox.critical(self, "Error", "Minecraft version is required!")
                return

            # Group entries
            mods = []
            resourcepacks = []
            shaderpacks = []

            for i in range(self.mod_list.count()):
                item = self.mod_list.item(i)
                m_type, slug = item.data(Qt.ItemDataRole.UserRole)
                if m_type == "Mods":
                    mods.append(slug)
                elif m_type == "Resourcepacks":
                    resourcepacks.append(slug)
                elif m_type == "Shaderpacks":
                    shaderpacks.append(slug)

            # Build config dict
            config = {
                "metadata": {
                    "name": self.name_edit.text(),
                    "version": self.version_edit.text(),
                    "description": self.desc_edit.toPlainText(),
                    "authors": self.authors_edit.text(),
                },
                "minecraft": {
                    "version": versions,
                    "mod_loader": self.loader_combo.currentText(),
                    "mods": mods,
                },
            }

            if resourcepacks:
                config["minecraft"]["resourcepacks"] = resourcepacks
            if shaderpacks:
                config["minecraft"]["shaderpacks"] = shaderpacks

            formats = []
            if self.format_zip.isChecked():
                formats.append("zip")
            if self.format_mrpack.isChecked():
                formats.append("mrpack")

            config["output"] = {
                "download_dir": self.download_dir_edit.text(),
                "format": formats,
            }

            # Save file
            file_path, _ = QFileDialog.getSaveFileName(
                self, "Save mods.toml", "mods.toml", "TOML files (*.toml)"
            )
            if file_path:
                with open(file_path, "w", encoding="utf-8") as f:
                    toml.dump(config, f)
                QMessageBox.information(self, "Success", f"Config saved to {file_path}")

        except Exception as e:
            QMessageBox.critical(self, "Error", f"An error occurred: {str(e)}")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = ModFetchGui()
    window.show()
    sys.exit(app.exec())
