# Minecraft 版本，例如 "1.20.1"
mc_version = ["1.20.1", "1.21.7"]

# 模组加载器，可选值: "fabric", "forge", "quilt"
mod_loader = "fabric"

# 模组下载目录，程序将在此目录下创建 'mods' 文件夹
download_dir = "./downloads"
mods = [
    "rei",
    "betterf3",
    "journeymap",
    "imblocker",
    "inventory-profiles-next",
    "appleskin",
    "blur-plus",
    "chat-heads",
    "dynamic-fps",
    "entityculling",
    "fabric-api",
    "ferrite-core",
    "iris",
    "jade",
    "lithium",
    "modmenu",
    "mouse-tweaks",
    "reeses-sodium-options",
    "sodium-extra",
    "sodium",
    "sound-physics-remastered",
]
