[metadata]
name = "test"
version = "0.1.0"
description = "A simple mod downloader"
authors = "A"

[minecraft]
# Minecraft 版本，例如 "1.20.1"
version = ["1.20.4", "1.21.7", "1.19.2", "1.20.1"]

# 模组加载器，可选值: "fabric", "forge", "quilt"
mod_loader = "fabric"

mods = [
    "rei",
    "betterf3",
    "journeymap",
    "imblocker-original",
    "inventory-profiles-next",
    "appleskin",
    "blur-plus",
    "chat-heads",
    "dynamic-fps",
    "entityculling",
    "fabric-api",
    "ferrite-core",
    "iris",
    "jade",
    "lithium",
    "modmenu",
    "mouse-tweaks",
    "reeses-sodium-options",
    "sodium-extra",
    "sodium",
    "sound-physics-remastered",
    "i18nupdatemod",
    "memoryleakfix",
    "distanthorizons",
    "controlling",
    "modernfix",
    "no-chat-reports",
    "starlight",
    "lazydfu",
    "krypton",
]

resourcepacks = [
    "even-better-enchants",
    "faithful-64x",
    "faithful-32x",
    "fast-better-grass",
    "3d-crops",
    "new-glowing-ores",
]

shaderpacks = ["complementary-reimagined", "vanilla-plus-shader"]

[output]
# 是否压缩
# 模组下载目录，程序将在此目录下创建 'mods' 文件夹
download_dir = "./downloads"
format = ["mrpack", "zip"]
