# Minecraft 版本，例如 "1.20.1"
mc_version = ["1.20.1"]

# 模组加载器，可选值: "fabric", "forge", "quilt" 等
mod_loader = "fabric"

# 模组下载目录，程序将在此目录下创建 'mods' 文件夹
download_dir = "./downloads" # 这是该配置文件的特定下载目录

mods = [
    "sodium",
    "iris",       # Iris 依赖 Sodium
    "lithium",
    "fabric-api", # 一个常见的 Fabric 模组依赖

]
