<script setup lang="ts">
import { useConfigStore } from '@/stores/config';
import McInput from '@/components/ui/McInput.vue';

const configStore = useConfigStore();
</script>

<template>
  <div class="metadata-form">
    <div class="metadata-form__field">
      <label class="metadata-form__label">包名称</label>
      <McInput v-model="configStore.config.metadata.name" placeholder="My Modpack" />
    </div>
    <div class="metadata-form__field">
      <label class="metadata-form__label">版本</label>
      <McInput v-model="configStore.config.metadata.version" placeholder="1.0.0" />
    </div>
    <div class="metadata-form__field">
      <label class="metadata-form__label">描述</label>
      <McInput v-model="configStore.config.metadata.description" placeholder="A modpack generated by ModFetch" />
    </div>
  </div>
</template>

<style scoped>
.metadata-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.metadata-form__field {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.metadata-form__label {
  font-family: 'Silkscreen', monospace;
  font-size: 10px;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
</style>
