name: Build and Upload Modfetch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build_for_platforms:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9"] # 指定 Python 3.9

    steps:
      - name: Checkout Code # 步骤1: 检出代码
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} # 步骤2: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and Nuitka with project dependencies # 步骤3: 安装 uv，Nuitka 和项目依赖
        run: |
          pip install uv
          # 创建虚拟环境
          uv venv
          uv sync --dev
        shell: bash

      - name: Make build.sh executable (Linux only) # 步骤4: 赋予 build.sh 脚本执行权限 (仅限Linux)
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x ./build.sh
        shell: bash

      - name: Run build script with uv # 步骤5: 运行 Nuitka 构建
        # 使用 uv run 来确保脚本在虚拟环境中运行，Nuitka 和所有依赖都可用。
        run: ./build.sh
        shell: bash

      - name: Rename and archive built executable # 步骤6: 重命名并打包可执行文件
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Nuitka 在 Linux 上生成名为 'modfetch' 的可执行文件
            mv modfetch.bin modfetch-linux
            tar -czf modfetch-linux.tar.gz modfetch-linux
          else
            # Nuitka 在 Windows 上生成名为 'modfetch.exe' 的可执行文件
            mv modfetch.exe modfetch-windows.exe
            7z a modfetch-windows.zip modfetch-windows.exe
          fi
        shell: bash

      - name: Upload modfetch artifact # 步骤7: 上传打包好的可执行文件
        uses: actions/upload-artifact@v4
        with:
          name: modfetch-build-output-${{ matrix.os }} # 更改名称以反映是构建输出
          path: |
            modfetch-linux.tar.gz
            modfetch-windows.zip
          retention-days: 7 # 构建产物保留7天
